In [10]:

# coding: utf-8
import sys, os
sys.path.append(os.pardir)  # 부모 디렉터리의 파일을 가져올 수 있도록 설정


In [11]:

def mean_squared_error(y, t):
    return 0.5 * np.sum((y-t)**2)

def sigmoid(x):
    return 1 / (1 + np.exp(-x))    

def numerical_gradient(f, x):
    h = 1e-4 # 0.0001
    grad = np.zeros_like(x)

    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    while not it.finished:
        idx = it.multi_index
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + h
        fxh1 = f(x) # f(x+h)

        x[idx] = tmp_val - h 
        fxh2 = f(x) # f(x-h)
        grad[idx] = (fxh1 - fxh2) / (2*h)

        x[idx] = tmp_val # 값 복원
        it.iternext()   

    return grad

class XorLayerNet:

    def __init__(self, input_size, hidden_size, output_size, weight_init_std=0.01):
        # 가중치 초기화
        self.params = {}
        self.params['W1'] = np.random.randn(input_size, hidden_size) / np.sqrt(input_size)
        self.params['b1'] = np.zeros(hidden_size)
        xavier_init = np.sqrt(output_size)
        self.params['W2'] = np.random.randn(hidden_size, output_size) / np.sqrt(hidden_size)
        self.params['b2'] = np.zeros(output_size)

    def predict(self, x):
        W1, W2 = self.params['W1'], self.params['W2']
        b1, b2 = self.params['b1'], self.params['b2']
    
        a1 = np.dot(x, W1) + b1
        z1 = sigmoid(a1)
        a2 = np.dot(z1, W2) + b2
        y = a2
        
        return y
        
    # x : 입력 데이터, t : 정답 레이블
    def loss(self, x, t):
        y = self.predict(x)
        
        return mean_squared_error(y, t)
    
    def accuracy(self, x, t):
        y = self.predict(x)
        y = np.argmax(y, axis=1)
        t = np.argmax(t, axis=1)
        
        accuracy = np.sum(y == t) / float(x.shape[0])
        return accuracy
        
    # x : 입력 데이터, t : 정답 레이블
    def numerical_gradient(self, x, t):
        loss_W = lambda W: self.loss(x, t)
        
        grads = {}
        grads['W1'] = numerical_gradient(loss_W, self.params['W1'])
        grads['b1'] = numerical_gradient(loss_W, self.params['b1'])
        grads['W2'] = numerical_gradient(loss_W, self.params['W2'])
        grads['b2'] = numerical_gradient(loss_W, self.params['b2'])
        
        return grads
        
    def gradient(self, x, t):
        W1, W2 = self.params['W1'], self.params['W2']
        b1, b2 = self.params['b1'], self.params['b2']
        grads = {}
        
        batch_num = x.shape[0]
        
        # forward
        a1 = np.dot(x, W1) + b1
        z1 = sigmoid(a1)
        a2 = np.dot(z1, W2) + b2
        y = softmax(a2)
        
        # backward
        dy = (y - t) / batch_num
        grads['W2'] = np.dot(z1.T, dy)
        grads['b2'] = np.sum(dy, axis=0)
        
        da1 = np.dot(dy, W2.T)
        dz1 = sigmoid_grad(a1) * da1
        grads['W1'] = np.dot(x.T, dz1)
        grads['b1'] = np.sum(dz1, axis=0)

        return grads
    
network = XorLayerNet(input_size=2, hidden_size=10, output_size=1)
x_train =  np.array([[0,0],[0,1],[1,0],[1,1]])
t_train = np.array([0,1,1,0])

# 하이퍼파라미터
iters_num = 50000  # 반복 횟수를 적절히 설정한다.
train_size = 4
batch_size = 1   # 미니배치 크기
learning_rate = 0.01

train_loss_list = []
train_acc_list = []
test_acc_list = []

# 1에폭당 반복 수
iter_per_epoch = max(train_size / batch_size, 1)
batch_mask = np.random.choice(train_size, batch_size)

for i in range(iters_num):
    # 미니배치 획득
    batch_mask = np.random.choice(train_size, batch_size)

    x_batch = x_train[batch_mask]
    t_batch = t_train[batch_mask]
    
    # 기울기 계산
    grad = network.numerical_gradient(x_batch, t_batch)
    #grad = network.gradient(x_batch, t_batch)
    
    # 매개변수 갱신
    for key in ('W1', 'b1', 'W2', 'b2'):
        network.params[key] -= learning_rate * grad[key]
    
    # 학습 경과 기록
    loss = network.loss(x_batch, t_batch)
    #print("loss : %0.005f"+ loss + " x_batch" + x_batch + " predict = "+ network.predict(x_batch) + " correct = "% t_batch)
    print("-------------")
    print(x_batch)
    print(loss)
    print(network.predict(x_batch))
    #print(t_batch)
    print("-------------")
    train_loss_list.append(loss)
    




-------------
[[0 0]]
0.403222750538
[[-0.89802311]]
-------------
-------------
[[0 1]]
2.10077747301
[[-1.04976949]]
-------------
-------------
[[1 0]]
1.81800530966
[[-0.90683261]]
-------------
-------------
[[1 0]]
1.6582674431
[[-0.8211356]]
-------------
-------------
[[1 0]]
1.51278614813
[[-0.73941723]]
-------------
-------------
[[1 1]]
0.365210723461
[[-0.85464697]]
-------------
-------------
[[0 0]]
0.143606861315
[[-0.53592324]]
-------------
-------------
[[0 0]]
0.133611056204
[[-0.51693531]]
-------------
-------------
[[0 0]]
0.124313175567
[[-0.49862446]]
-------------
-------------
[[1 0]]
1.21874773858
[[-0.56124805]]
-------------
-------------
[[0 1]]
1.2217544994
[[-0.56317273]]
-------------
-------------
[[0 1]]
1.11914193088
[[-0.49608952]]
-------------
-------------
[[1 1]]
0.143902016445
[[-0.5364737]]
-------------
-------------
[[0 1]]
0.989838542101
[[-0.40700998]]
-------------
-------------
[[0 0]]
0.0257106195578
[[-0.22676252]]
-------------
-----

[[ 0.55204834]]
-------------
-------------
[[0 1]]
0.102196618882
[[ 0.5479013]]
-------------
-------------
[[0 0]]
0.176829770403
[[ 0.59469281]]
-------------
-------------
[[0 0]]
0.164590070517
[[ 0.57374223]]
-------------
-------------
[[0 0]]
0.153198472343
[[ 0.55353134]]
-------------
-------------
[[1 1]]
0.113329204274
[[ 0.47608656]]
-------------
-------------
[[0 1]]
0.134896278333
[[ 0.48058441]]
-------------
-------------
[[1 1]]
0.113132593915
[[ 0.4756734]]
-------------
-------------
[[1 0]]
0.0963232017689
[[ 0.56108497]]
-------------
-------------
[[1 1]]
0.11136291095
[[ 0.47193837]]
-------------
-------------
[[1 1]]
0.100370590092
[[ 0.44804149]]
-------------
-------------
[[0 0]]
0.122007185422
[[ 0.49397811]]
-------------
-------------
[[0 1]]
0.157850687365
[[ 0.43812691]]
-------------
-------------
[[0 1]]
0.144654099278
[[ 0.46212622]]
-------------
-------------
[[0 0]]
0.134386859157
[[ 0.51843391]]
-------------
-------------
[[0 1]]
0.1427521338

0.179590828725
[[ 0.59931766]]
-------------
-------------
[[1 1]]
0.14851186147
[[ 0.54499883]]
-------------
-------------
[[1 1]]
0.133867331539
[[ 0.51743083]]
-------------
-------------
[[1 0]]
0.0846443547676
[[ 0.58855291]]
-------------
-------------
[[1 0]]
0.077293508042
[[ 0.60682445]]
-------------
-------------
[[1 1]]
0.139669008869
[[ 0.52852438]]
-------------
-------------
[[1 0]]
0.0802072535406
[[ 0.5994822]]
-------------
-------------
[[0 1]]
0.104200645116
[[ 0.5434901]]
-------------
-------------
[[0 0]]
0.166669463942
[[ 0.57735511]]
-------------
-------------
[[1 1]]
0.134246042795
[[ 0.51816222]]
-------------
-------------
[[0 1]]
0.116482013658
[[ 0.51733653]]
-------------
-------------
[[1 1]]
0.132074501207
[[ 0.51395428]]
-------------
-------------
[[0 0]]
0.142020919809
[[ 0.53295576]]
-------------
-------------
[[1 0]]
0.0942521669398
[[ 0.56582914]]
-------------
-------------
[[0 0]]
0.141085262306
[[ 0.53119726]]
-------------
-------------
[[0

0.118156391629
[[ 0.48612013]]
-------------
-------------
[[1 1]]
0.0930112425109
[[ 0.43130324]]
-------------
-------------
[[0 1]]
0.15812205683
[[ 0.43764414]]
-------------
-------------
[[0 0]]
0.111714858997
[[ 0.47268353]]
-------------
-------------
[[0 1]]
0.154604573211
[[ 0.44393422]]
-------------
-------------
[[0 1]]
0.14170172032
[[ 0.4676435]]
-------------
-------------
[[1 0]]
0.0988224032614
[[ 0.55542739]]
-------------
-------------
[[0 0]]
0.132514426448
[[ 0.51480953]]
-------------
-------------
[[0 0]]
0.123358271038
[[ 0.49670569]]
-------------
-------------
[[1 0]]
0.107498139842
[[ 0.53632309]]
-------------
-------------
[[0 1]]
0.129576837001
[[ 0.49092862]]
-------------
-------------
[[1 0]]
0.0888947153652
[[ 0.57834916]]
-------------
-------------
[[0 0]]
0.142156878243
[[ 0.5332108]]
-------------
-------------
[[0 0]]
0.132334148367
[[ 0.51445923]]
-------------
-------------
[[1 1]]
0.109814890678
[[ 0.46864676]]
-------------
-------------
[[1 

[[0 0]]
0.11160169678
[[ 0.47244406]]
-------------
-------------
[[1 1]]
0.0979926409507
[[ 0.44270225]]
-------------
-------------
[[0 1]]
0.159633208795
[[ 0.43496335]]
-------------
-------------
[[1 0]]
0.109194382596
[[ 0.53267916]]
-------------
-------------
[[0 0]]
0.113952672409
[[ 0.47739433]]
-------------
-------------
[[0 1]]
0.145287869191
[[ 0.46094922]]
-------------
-------------
[[0 0]]
0.115723250928
[[ 0.48108887]]
-------------
-------------
[[0 0]]
0.107732188473
[[ 0.46418141]]
-------------
-------------
[[1 1]]
0.0948908251128
[[ 0.43563936]]
-------------
-------------
[[0 0]]
0.0924460920382
[[ 0.42999091]]
-------------
-------------
[[1 1]]
0.0786355127612
[[ 0.39657411]]
-------------
-------------
[[0 0]]
0.0794441452881
[[ 0.39860794]]
-------------
-------------
[[1 0]]
0.150802594737
[[ 0.45081407]]
-------------
-------------
[[1 0]]
0.137738639438
[[ 0.47514071]]
-------------
-------------
[[0 1]]
0.165594214609
[[ 0.42451027]]
-------------
-----

[[1 1]]
0.151991528103
[[ 0.55134658]]
-------------
-------------
[[1 1]]
0.137049614457
[[ 0.52354487]]
-------------
-------------
[[1 1]]
0.123578807825
[[ 0.49714949]]
-------------
-------------
[[0 0]]
0.110585372975
[[ 0.47028794]]
-------------
-------------
[[0 0]]
0.102952762673
[[ 0.45376814]]
-------------
-------------
[[1 1]]
0.0947806880866
[[ 0.43538647]]
-------------
-------------
[[0 0]]
0.0881897578885
[[ 0.41997561]]
-------------
-------------
[[1 0]]
0.134248447436
[[ 0.48183314]]
-------------
-------------
[[0 0]]
0.0905080271541
[[ 0.42545982]]
-------------
-------------
[[1 1]]
0.0815209210753
[[ 0.4037844]]
-------------
-------------
[[0 0]]
0.0776021792731
[[ 0.39395984]]
-------------
-------------
[[1 1]]
0.0676357179935
[[ 0.36779265]]
-------------
-------------
[[0 0]]
0.0666285637056
[[ 0.36504401]]
-------------
-------------
[[1 0]]
0.166288588475
[[ 0.42330495]]
-------------
-------------
[[1 0]]
0.151896424948
[[ 0.44882594]]
-------------
---

-------------
-------------
[[0 1]]
0.20231984966
[[ 0.36388704]]
-------------
-------------
[[0 0]]
0.0765398475519
[[ 0.391254]]
-------------
-------------
[[0 1]]
0.194473461775
[[ 0.37634391]]
-------------
-------------
[[0 1]]
0.178273209975
[[ 0.40288492]]
-------------
-------------
[[1 1]]
0.089388217538
[[ 0.42281962]]
-------------
-------------
[[0 1]]
0.174772605214
[[ 0.40877651]]
-------------
-------------
[[0 0]]
0.0919887501223
[[ 0.42892598]]
-------------
-------------
[[0 1]]
0.169409961926
[[ 0.4179176]]
-------------
-------------
[[0 1]]
0.15529593197
[[ 0.44269231]]
-------------
-------------
[[0 1]]
0.142356658883
[[ 0.46641466]]
-------------
-------------
[[1 0]]
0.0931200063212
[[ 0.56844466]]
-------------
-------------
[[0 1]]
0.121351367694
[[ 0.50735131]]
-------------
-------------
[[0 1]]
0.111237674408
[[ 0.52832707]]
-------------
-------------
[[1 0]]
0.0691510011071
[[ 0.62811023]]
-------------
-------------
[[0 0]]
0.148663977869
[[ 0.5452778

-------------
[[1 0]]
0.072035723293
[[ 0.62043255]]
-------------
-------------
[[0 1]]
0.0905150311179
[[ 0.57452372]]
-------------
-------------
[[1 1]]
0.179239664781
[[ 0.59873143]]
-------------
-------------
[[1 1]]
0.161648984114
[[ 0.56859297]]
-------------
-------------
[[0 1]]
0.106383934503
[[ 0.53873232]]
-------------
-------------
[[0 0]]
0.134508961564
[[ 0.51866938]]
-------------
-------------
[[0 0]]
0.125232966975
[[ 0.50046572]]
-------------
-------------
[[0 1]]
0.115054386277
[[ 0.52030346]]
-------------
-------------
[[1 0]]
0.0795324289919
[[ 0.60117064]]
-------------
-------------
[[1 0]]
0.072658853628
[[ 0.6187944]]
-------------
-------------
[[0 0]]
0.141257467021
[[ 0.53152134]]
-------------
-------------
[[1 1]]
0.155204330107
[[ 0.5571433]]
-------------
-------------
[[1 0]]
0.0843459424613
[[ 0.58927882]]
-------------
-------------
[[1 1]]
0.150169459277
[[ 0.54803186]]
-------------
-------------
[[1 0]]
0.0874295721241
[[ 0.58183838]]
-------

0.134040451254
[[ 0.5177653]]
-------------
-------------
[[0 1]]
0.0986881382505
[[ 0.5557295]]
-------------
-------------
[[0 0]]
0.133359413353
[[ 0.51644828]]
-------------
-------------
[[0 1]]
0.0988534056175
[[ 0.55535766]]
-------------
-------------
[[0 0]]
0.13271132496
[[ 0.51519186]]
-------------
-------------
[[0 0]]
0.123562029095
[[ 0.49711574]]
-------------
-------------
[[0 0]]
0.115044080915
[[ 0.47967506]]
-------------
-------------
[[0 1]]
0.115886946236
[[ 0.51857099]]
-------------
-------------
[[0 0]]
0.11573076574
[[ 0.48110449]]
-------------
-------------
[[0 1]]
0.114672196305
[[ 0.52110085]]
-------------
-------------
[[0 0]]
0.1163491323
[[ 0.48238809]]
-------------
-------------
[[0 1]]
0.11353782994
[[ 0.52347544]]
-------------
-------------
[[1 0]]
0.0816431717368
[[ 0.59591295]]
-------------
-------------
[[0 1]]
0.0964411730795
[[ 0.56081627]]
-------------
-------------
[[0 1]]
0.0884023785352
[[ 0.57951842]]
-------------
-------------
[[0 0

-------------
-------------
[[1 1]]
0.206175466423
[[ 0.64214557]]
-------------
-------------
[[1 0]]
0.0613593861302
[[ 0.64968761]]
-------------
-------------
[[0 1]]
0.0761603467111
[[ 0.60971716]]
-------------
-------------
[[0 1]]
0.0698110472718
[[ 0.6263396]]
-------------
-------------
[[1 0]]
0.0458190805897
[[ 0.69728204]]
-------------
-------------
[[1 1]]
0.227551493422
[[ 0.67461321]]
-------------
-------------
[[1 0]]
0.0514649870716
[[ 0.67917298]]
-------------
-------------
[[1 0]]
0.047020610896
[[ 0.69333859]]
-------------
-------------
[[0 1]]
0.0611225408468
[[ 0.65036436]]
-------------
-------------
[[0 1]]
0.0560257394229
[[ 0.66525909]]
-------------
-------------
[[1 0]]
0.0349360605016
[[ 0.73566665]]
-------------
-------------
[[1 1]]
0.25406653033
[[ 0.71283453]]
-------------
-------------
[[0 1]]
0.0585631838734
[[ 0.6577627]]
-------------
-------------
[[1 0]]
0.0368639776775
[[ 0.72847108]]
-------------
-------------
[[1 1]]
0.248532557102
[[ 0

[[ 0.45644986]]
-------------
-------------
[[1 0]]
0.133557084519
[[ 0.48316911]]
-------------
-------------
[[0 1]]
0.150754427924
[[ 0.45090178]]
-------------
-------------
[[1 1]]
0.116263274004
[[ 0.48221007]]
-------------
-------------
[[0 1]]
0.1501329165
[[ 0.45203483]]
-------------
-------------
[[0 1]]
0.137626862885
[[ 0.47535371]]
-------------
-------------
[[0 1]]
0.126161487917
[[ 0.4976824]]
-------------
-------------
[[0 0]]
0.103414335039
[[ 0.4547842]]
-------------
-------------
[[0 0]]
0.0962895759738
[[ 0.43883841]]
-------------
-------------
[[1 1]]
0.122042205539
[[ 0.494049]]
-------------
-------------
[[1 0]]
0.117332436982
[[ 0.51557779]]
-------------
-------------
[[0 0]]
0.0890910641844
[[ 0.42211625]]
-------------
-------------
[[0 1]]
0.141725650512
[[ 0.46759855]]
-------------
-------------
[[1 0]]
0.104340844718
[[ 0.54318309]]
-------------
-------------
[[1 1]]
0.135181488901
[[ 0.5199644]]
-------------
-------------
[[1 0]]
0.106212973508


-------------
[[0 1]]
0.07068343418
[[ 0.62401214]]
-------------
-------------
[[1 1]]
0.21889011487
[[ 0.66164963]]
-------------
-------------
[[1 0]]
0.056466225812
[[ 0.66394576]]
-------------
-------------
[[1 1]]
0.207291018164
[[ 0.64388045]]
-------------
-------------
[[0 1]]
0.0824250767456
[[ 0.59398257]]
-------------
-------------
[[1 1]]
0.198434825056
[[ 0.62997591]]
-------------
-------------
[[0 0]]
0.129267428459
[[ 0.50846323]]
-------------
-------------
[[1 1]]
0.167166616395
[[ 0.57821556]]
-------------
-------------
[[1 0]]
0.0839983764742
[[ 0.59012593]]
-------------
-------------
[[1 0]]
0.0767545912537
[[ 0.60819752]]
-------------
-------------
[[0 0]]
0.124107914444
[[ 0.49821263]]
-------------
-------------
[[1 0]]
0.0774465892395
[[ 0.60643529]]
-------------
-------------
[[0 1]]
0.0931505895908
[[ 0.5683738]]
-------------
-------------
[[1 0]]
0.0641077656174
[[ 0.64192804]]
-------------
-------------
[[0 1]]
0.0792620586828
[[ 0.60184913]]
-----

[[ 0.53530103]]
-------------
-------------
[[0 1]]
0.0845336138058
[[ 0.58882215]]
-------------
-------------
[[1 0]]
0.0560392317082
[[ 0.66521878]]
-------------
-------------
[[0 0]]
0.148593803461
[[ 0.54514916]]
-------------
-------------
[[0 0]]
0.13835644656
[[ 0.52603507]]
-------------
-------------
[[0 0]]
0.128825205942
[[ 0.50759276]]
-------------
-------------
[[1 0]]
0.0723287492683
[[ 0.61966134]]
-------------
-------------
[[0 1]]
0.0892323387994
[[ 0.5775492]]
-------------
-------------
[[1 0]]
0.059797599972
[[ 0.65417461]]
-------------
-------------
[[1 0]]
0.0546418064948
[[ 0.66941928]]
-------------
-------------
[[0 0]]
0.14957169329
[[ 0.54694002]]
-------------
-------------
[[0 0]]
0.139266985913
[[ 0.52776318]]
-------------
-------------
[[0 0]]
0.129673051305
[[ 0.50926035]]
-------------
-------------
[[0 1]]
0.0946419889923
[[ 0.56493221]]
-------------
-------------
[[1 0]]
0.064168683604
[[ 0.64175795]]
-------------
-------------
[[0 1]]
0.08057

[[ 0.53961314]]
-------------
-------------
[[1 1]]
0.166894666468
[[ 0.57774504]]
-------------
-------------
[[0 0]]
0.106927278827
[[ 0.46244411]]
-------------
-------------
[[1 1]]
0.140709998665
[[ 0.53049034]]
-------------
-------------
[[0 0]]
0.0901338756349
[[ 0.4245795]]
-------------
-------------
[[1 0]]
0.108161802041
[[ 0.53489399]]
-------------
-------------
[[1 0]]
0.0988426205874
[[ 0.55538192]]
-------------
-------------
[[0 1]]
0.118393781962
[[ 0.51339178]]
-------------
-------------
[[1 1]]
0.151767290978
[[ 0.55093973]]
-------------
-------------
[[1 0]]
0.0925456588984
[[ 0.56977759]]
-------------
-------------
[[1 1]]
0.147468755999
[[ 0.5430815]]
-------------
-------------
[[0 0]]
0.0948726335628
[[ 0.4355976]]
-------------
-------------
[[1 0]]
0.102678282747
[[ 0.54683715]]
-------------
-------------
[[0 1]]
0.122673609907
[[ 0.50467463]]
-------------
-------------
[[1 0]]
0.0850360306768
[[ 0.58760206]]
-------------
-------------
[[0 0]]
0.111756

0.0755483753523
[[ 0.38871165]]
-------------
-------------
[[0 0]]
0.0703473690392
[[ 0.37509297]]
-------------
-------------
[[1 1]]
0.0897483898657
[[ 0.4236706]]
-------------
-------------
[[0 0]]
0.059397733223
[[ 0.34466718]]
-------------
-------------
[[0 0]]
0.0553089514506
[[ 0.3325927]]
-------------
-------------
[[1 1]]
0.0705692087989
[[ 0.37568393]]
-------------
-------------
[[1 1]]
0.0636803049281
[[ 0.35687618]]
-------------
-------------
[[1 1]]
0.0574639792617
[[ 0.33901026]]
-------------
-------------
[[0 1]]
0.226451751557
[[ 0.32701894]]
-------------
-------------
[[0 0]]
0.0458187720566
[[ 0.30271694]]
-------------
-------------
[[1 0]]
0.181112532708
[[ 0.39814864]]
-------------
-------------
[[1 0]]
0.165519550038
[[ 0.42464003]]
-------------
-------------
[[1 0]]
0.151268836046
[[ 0.44996575]]
-------------
-------------
[[0 0]]
0.0645366837344
[[ 0.35926782]]
-------------
-------------
[[1 1]]
0.0822574020928
[[ 0.40560425]]
-------------
---------

-------------
[[0 0]]
0.130095548226
[[ 0.5100893]]
-------------
-------------
[[1 1]]
0.177020330025
[[ 0.59501316]]
-------------
-------------
[[0 1]]
0.10088187151
[[ 0.55081881]]
-------------
-------------
[[1 1]]
0.171454975288
[[ 0.58558514]]
-------------
-------------
[[0 0]]
0.106295525268
[[ 0.46107597]]
-------------
-------------
[[1 0]]
0.0895992492504
[[ 0.57668156]]
-------------
-------------
[[1 1]]
0.155381583187
[[ 0.55746136]]
-------------
-------------
[[1 1]]
0.140215060685
[[ 0.52955653]]
-------------
-------------
[[0 1]]
0.128240639862
[[ 0.49356019]]
-------------
-------------
[[0 0]]
0.0951475226247
[[ 0.4362282]]
-------------
-------------
[[0 1]]
0.125572277904
[[ 0.49885675]]
-------------
-------------
[[0 1]]
0.115103629108
[[ 0.52020081]]
-------------
-------------
[[0 0]]
0.104933305574
[[ 0.45811201]]
-------------
-------------
[[1 0]]
0.0911040828873
[[ 0.57314152]]
-------------
-------------
[[1 1]]
0.15384095787
[[ 0.55469083]]
----------

-------------
-------------
[[1 0]]
0.064143301765
[[ 0.64182881]]
-------------
-------------
[[1 0]]
0.0586218330112
[[ 0.65759138]]
-------------
-------------
[[0 0]]
0.140017144518
[[ 0.52918266]]
-------------
-------------
[[1 1]]
0.19327578668
[[ 0.62173272]]
-------------
-------------
[[0 0]]
0.117750108452
[[ 0.48528365]]
-------------
-------------
[[1 1]]
0.163274166431
[[ 0.57144408]]
-------------
-------------
[[1 0]]
0.0888171781295
[[ 0.57853309]]
-------------
-------------
[[1 1]]
0.158021584055
[[ 0.56217717]]
-------------
-------------
[[0 0]]
0.0961141407454
[[ 0.43843846]]
-------------
-------------
[[1 0]]
0.0993493123515
[[ 0.55424376]]
-------------
-------------
[[0 1]]
0.112444724623
[[ 0.5257749]]
-------------
-------------
[[1 1]]
0.15604859451
[[ 0.55865659]]
-------------
-------------
[[1 1]]
0.140825106169
[[ 0.53070728]]
-------------
-------------
[[1 0]]
0.104340850965
[[ 0.54318308]]
-------------
-------------
[[1 0]]
0.0953616787333
[[ 0.5632

0.187383144213
[[ 0.61218158]]
-------------
-------------
[[1 0]]
0.0764897322433
[[ 0.60887411]]
-------------
-------------
[[0 0]]
0.11289598909
[[ 0.47517573]]
-------------
-------------
[[0 1]]
0.0969526791637
[[ 0.55965314]]
-------------
-------------
[[0 1]]
0.0888620094187
[[ 0.57842673]]
-------------
-------------
[[0 1]]
0.081445774906
[[ 0.59640175]]
-------------
-------------
[[1 0]]
0.0574221317957
[[ 0.6611132]]
-------------
-------------
[[1 1]]
0.213610970033
[[ 0.65362217]]
-------------
-------------
[[0 1]]
0.0808879160452
[[ 0.59778634]]
-------------
-------------
[[0 1]]
0.0741364506667
[[ 0.6149378]]
-------------
-------------
[[1 0]]
0.0516026008559
[[ 0.67874434]]
-------------
-------------
[[0 1]]
0.0630498423222
[[ 0.64489483]]
-------------
-------------
[[1 0]]
0.0426899823691
[[ 0.7078015]]
-------------
-------------
[[1 0]]
0.0390148004539
[[ 0.72066221]]
-------------
-------------
[[1 0]]
0.0356558002135
[[ 0.73295768]]
-------------
----------

-------------
-------------
[[0 0]]
0.102316151361
[[ 0.45236302]]
-------------
-------------
[[1 1]]
0.15397374321
[[ 0.55493016]]
-------------
-------------
[[0 1]]
0.118386544445
[[ 0.51340665]]
-------------
-------------
[[0 0]]
0.0934609452471
[[ 0.43234464]]
-------------
-------------
[[0 0]]
0.0870271955217
[[ 0.41719826]]
-------------
-------------
[[0 1]]
0.123772070934
[[ 0.50246192]]
-------------
-------------
[[0 0]]
0.088805556383
[[ 0.42143933]]
-------------
-------------
[[0 0]]
0.0826925004551
[[ 0.40667555]]
-------------
-------------
[[0 1]]
0.128634058135
[[ 0.49278396]]
-------------
-------------
[[1 0]]
0.0989189621447
[[ 0.55521025]]
-------------
-------------
[[1 1]]
0.150655194357
[[ 0.54891747]]
-------------
-------------
[[1 1]]
0.135967615105
[[ 0.52147409]]
-------------
-------------
[[0 0]]
0.0742356264316
[[ 0.38531968]]
-------------
-------------
[[0 0]]
0.0691260271797
[[ 0.37182261]]
-------------
-------------
[[0 0]]
0.0643682852405
[[ 0.

-------------
[[1 0]]
0.0811566523233
[[ 0.59711875]]
-------------
-------------
[[1 0]]
0.0741732806279
[[ 0.61484216]]
-------------
-------------
[[0 1]]
0.0844469202495
[[ 0.58903304]]
-------------
-------------
[[0 0]]
0.121019339614
[[ 0.49197427]]
-------------
-------------
[[0 1]]
0.0847852157983
[[ 0.5882107]]
-------------
-------------
[[0 0]]
0.120219596472
[[ 0.49034599]]
-------------
-------------
[[0 1]]
0.0850845122411
[[ 0.58748452]]
-------------
-------------
[[0 1]]
0.0779764413261
[[ 0.6050913]]
-------------
-------------
[[0 0]]
0.126895148056
[[ 0.50377604]]
-------------
-------------
[[0 0]]
0.11815668569
[[ 0.48612074]]
-------------
-------------
[[0 1]]
0.0861124482623
[[ 0.58500012]]
-------------
-------------
[[0 0]]
0.117525125486
[[ 0.48481981]]
-------------
-------------
[[0 0]]
0.1094325891
[[ 0.46783029]]
-------------
-------------
[[1 1]]
0.172192652057
[[ 0.58684351]]
-------------
-------------
[[1 0]]
0.0886483732659
[[ 0.5789338]]
-------

-------------
[[0 0]]
0.102214731013
[[ 0.45213876]]
-------------
-------------
[[0 0]]
0.0951763803988
[[ 0.43629435]]
-------------
-------------
[[1 1]]
0.147166482813
[[ 0.54252462]]
-------------
-------------
[[0 1]]
0.121740396526
[[ 0.50656227]]
-------------
-------------
[[0 0]]
0.0872031661007
[[ 0.41761984]]
-------------
-------------
[[0 1]]
0.119051366371
[[ 0.51204228]]
-------------
-------------
[[0 0]]
0.0888265711498
[[ 0.4214892]]
-------------
-------------
[[1 0]]
0.100786852515
[[ 0.5510304]]
-------------
-------------
[[1 1]]
0.149802240359
[[ 0.54736138]]
-------------
-------------
[[0 1]]
0.119629522945
[[ 0.51085887]]
-------------
-------------
[[1 1]]
0.146987132468
[[ 0.54219394]]
-------------
-------------
[[1 0]]
0.105437192519
[[ 0.54078939]]
-------------
-------------
[[0 0]]
0.0866000419809
[[ 0.41617314]]
-------------
-------------
[[0 1]]
0.119759035356
[[ 0.51059417]]
-------------
-------------
[[0 0]]
0.0882622559571
[[ 0.4201482]]
-------

0.140280087553
[[ 0.47032069]]
-------------
-------------
[[0 0]]
0.0643433438423
[[ 0.35872927]]
-------------
-------------
[[0 1]]
0.150040028139
[[ 0.45220437]]
-------------
-------------
[[1 0]]
0.123520040612
[[ 0.50296873]]
-------------
-------------
[[0 1]]
0.126727410628
[[ 0.49655703]]
-------------
-------------
[[0 1]]
0.116130232532
[[ 0.51806591]]
-------------
-------------
[[1 0]]
0.0940652278945
[[ 0.56625992]]
-------------
-------------
[[0 1]]
0.0981496294599
[[ 0.55694328]]
-------------
-------------
[[1 0]]
0.0784198573432
[[ 0.60397006]]
-------------
-------------
[[1 1]]
0.181250815388
[[ 0.60208108]]
-------------
-------------
[[0 1]]
0.0946827921836
[[ 0.56483844]]
-------------
-------------
[[1 1]]
0.175080350665
[[ 0.59174378]]
-------------
-------------
[[1 0]]
0.086399713477
[[ 0.5843085]]
-------------
-------------
[[1 0]]
0.0789649487785
[[ 0.60259605]]
-------------
-------------
[[0 0]]
0.111461605041
[[ 0.47214745]]
-------------
------------

-------------
-------------
[[1 0]]
0.089280781717
[[ 0.57743455]]
-------------
-------------
[[1 0]]
0.0815983889726
[[ 0.59602379]]
-------------
-------------
[[0 0]]
0.104919387346
[[ 0.45808162]]
-------------
-------------
[[0 1]]
0.0936106157395
[[ 0.56730931]]
-------------
-------------
[[0 1]]
0.085777133631
[[ 0.5858089]]
-------------
-------------
[[1 1]]
0.190482968162
[[ 0.61722438]]
-------------
-------------
[[0 0]]
0.100812425294
[[ 0.44902656]]
-------------
-------------
[[1 0]]
0.0856198468143
[[ 0.58618882]]
-------------
-------------
[[1 0]]
0.0782523557095
[[ 0.60439324]]
-------------
-------------
[[1 1]]
0.183465627849
[[ 0.60574851]]
-------------
-------------
[[1 1]]
0.16559867916
[[ 0.57549749]]
-------------
-------------
[[1 0]]
0.0937387144491
[[ 0.56701336]]
-------------
-------------
[[1 0]]
0.0856727607954
[[ 0.58606097]]
-------------
-------------
[[0 1]]
0.0908469013121
[[ 0.57374444]]
-------------
-------------
[[1 0]]
0.0713673376696
[[ 0.

[[ 0.52216534]]
-------------
-------------
[[1 1]]
0.135206216394
[[ 0.52001195]]
-------------
-------------
[[0 0]]
0.0680724310936
[[ 0.36897813]]
-------------
-------------
[[0 1]]
0.138532443178
[[ 0.47363047]]
-------------
-------------
[[0 1]]
0.126936462352
[[ 0.49614196]]
-------------
-------------
[[1 1]]
0.138461916101
[[ 0.52623553]]
-------------
-------------
[[1 1]]
0.124982245786
[[ 0.49996449]]
-------------
-------------
[[1 0]]
0.124623082383
[[ 0.5007544]]
-------------
-------------
[[0 1]]
0.129297456454
[[ 0.49147772]]
-------------
-------------
[[0 0]]
0.0768551323656
[[ 0.39205901]]
-------------
-------------
[[0 0]]
0.0715614288706
[[ 0.37831582]]
-------------
-------------
[[1 1]]
0.120316285419
[[ 0.49054314]]
-------------
-------------
[[0 1]]
0.144795488818
[[ 0.46186342]]
-------------
-------------
[[0 0]]
0.0667983238261
[[ 0.36550875]]
-------------
-------------
[[0 0]]
0.0621976308563
[[ 0.35269712]]
-------------
-------------
[[0 0]]
0.0579

[[ 0.39626606]]
-------------
-------------
[[0 1]]
0.115595484971
[[ 0.51917678]]
-------------
-------------
[[1 1]]
0.148264387002
[[ 0.54454456]]
-------------
-------------
[[0 1]]
0.117772482259
[[ 0.51467025]]
-------------
-------------
[[0 0]]
0.0787600892423
[[ 0.39688812]]
-------------
-------------
[[0 1]]
0.114902174321
[[ 0.52062087]]
-------------
-------------
[[0 0]]
0.0804689556135
[[ 0.40117068]]
-------------
-------------
[[0 0]]
0.0749245757357
[[ 0.38710354]]
-------------
-------------
[[1 1]]
0.132299317747
[[ 0.51439152]]
-------------
-------------
[[0 1]]
0.131076195527
[[ 0.48799181]]
-------------
-------------
[[0 0]]
0.0692043131664
[[ 0.3720331]]
-------------
-------------
[[0 1]]
0.127001214181
[[ 0.49601346]]
-------------
-------------
[[0 0]]
0.0714879438828
[[ 0.37812153]]
-------------
-------------
[[0 0]]
0.0665626402191
[[ 0.36486337]]
-------------
-------------
[[1 0]]
0.124312063966
[[ 0.50137777]]
-------------
-------------
[[0 1]]
0.119

-------------
[[1 0]]
0.0773213444185
[[ 0.60675365]]
-------------
-------------
[[0 0]]
0.105575013323
[[ 0.45951064]]
-------------
-------------
[[0 0]]
0.0982975227045
[[ 0.4433904]]
-------------
-------------
[[0 1]]
0.0913480989709
[[ 0.57257024]]
-------------
-------------
[[1 1]]
0.179632855732
[[ 0.59938778]]
-------------
-------------
[[1 1]]
0.162148335371
[[ 0.56947052]]
-------------
-------------
[[1 0]]
0.099717414947
[[ 0.55341873]]
-------------
-------------
[[0 1]]
0.098629608063
[[ 0.55586126]]
-------------
-------------
[[1 1]]
0.169168502948
[[ 0.58166744]]
-------------
-------------
[[0 0]]
0.0828478767987
[[ 0.40705743]]
-------------
-------------
[[0 0]]
0.0771379420205
[[ 0.39277969]]
-------------
-------------
[[1 1]]
0.135761027031
[[ 0.52107778]]
-------------
-------------
[[1 1]]
0.122546357391
[[ 0.49506839]]
-------------
-------------
[[1 1]]
0.110617584093
[[ 0.47035643]]
-------------
-------------
[[0 0]]
0.0507250514212
[[ 0.31851233]]
----

0.0742077638052
[[ 0.61475264]]
-------------
-------------
[[0 0]]
0.104951070756
[[ 0.45815078]]
-------------
-------------
[[1 1]]
0.186052998686
[[ 0.61000492]]
-------------
-------------
[[1 0]]
0.0857174933542
[[ 0.58595292]]
-------------
-------------
[[1 0]]
0.0783359290971
[[ 0.60418204]]
-------------
-------------
[[0 1]]
0.0781679679524
[[ 0.60460661]]
-------------
-------------
[[0 0]]
0.107533357543
[[ 0.46375286]]
-------------
-------------
[[0 0]]
0.10011850552
[[ 0.4474785]]
-------------
-------------
[[1 0]]
0.0786063060168
[[ 0.60349954]]
-------------
-------------
[[1 0]]
0.0718370354907
[[ 0.62095637]]
-------------
-------------
[[1 0]]
0.0656505438174
[[ 0.63764508]]
-------------
-------------
[[0 1]]
0.0664155608546
[[ 0.63553996]]
-------------
-------------
[[1 1]]
0.222666574572
[[ 0.66733286]]
-------------
-------------
[[0 1]]
0.0720449411291
[[ 0.62040827]]
-------------
-------------
[[0 0]]
0.113822111297
[[ 0.47712076]]
-------------
----------

-------------
-------------
[[0 1]]
0.0983175015189
[[ 0.55656454]]
-------------
-------------
[[1 0]]
0.0835926685064
[[ 0.59111696]]
-------------
-------------
[[1 0]]
0.0763912369143
[[ 0.60912601]]
-------------
-------------
[[1 1]]
0.192561971807
[[ 0.62058355]]
-------------
-------------
[[0 1]]
0.0878785934689
[[ 0.58076595]]
-------------
-------------
[[1 1]]
0.185238320771
[[ 0.60866792]]
-------------
-------------
[[1 1]]
0.167212821793
[[ 0.57829546]]
-------------
-------------
[[0 1]]
0.103956698409
[[ 0.54402478]]
-------------
-------------
[[0 0]]
0.0839875790535
[[ 0.40984773]]
-------------
-------------
[[0 1]]
0.102031447909
[[ 0.54826679]]
-------------
-------------
[[1 0]]
0.0870227372784
[[ 0.58281242]]
-------------
-------------
[[1 0]]
0.0795255465348
[[ 0.6011879]]
-------------
-------------
[[1 0]]
0.0726741376354
[[ 0.61875431]]
-------------
-------------
[[0 0]]
0.105420240181
[[ 0.45917369]]
-------------
-------------
[[0 1]]
0.0795759979697
[[ 

-------------
[[1 1]]
0.148160221399
[[ 0.54435323]]
-------------
-------------
[[1 1]]
0.13374067455
[[ 0.51718599]]
-------------
-------------
[[1 0]]
0.128275128336
[[ 0.4934921]]
-------------
-------------
[[0 1]]
0.118252866578
[[ 0.51368145]]
-------------
-------------
[[0 0]]
0.0673336934901
[[ 0.36697055]]
-------------
-------------
[[1 1]]
0.136354879369
[[ 0.5222162]]
-------------
-------------
[[0 0]]
0.0553923089526
[[ 0.33284323]]
-------------
-------------
[[0 1]]
0.132972851713
[[ 0.48430076]]
-------------
-------------
[[0 1]]
0.121793616132
[[ 0.50645443]]
-------------
-------------
[[0 1]]
0.111553740336
[[ 0.52765745]]
-------------
-------------
[[1 0]]
0.102212494277
[[ 0.54786618]]
-------------
-------------
[[0 0]]
0.0780419204317
[[ 0.39507448]]
-------------
-------------
[[1 1]]
0.154300353348
[[ 0.55551841]]
-------------
-------------
[[1 1]]
0.139283105599
[[ 0.52779372]]
-------------
-------------
[[0 0]]
0.056829515513
[[ 0.33713355]]
---------

[[0 1]]
0.103369399638
[[ 0.54531462]]
-------------
-------------
[[1 0]]
0.0918145991932
[[ 0.57148022]]
-------------
-------------
[[0 0]]
0.0859150185571
[[ 0.41452387]]
-------------
-------------
[[0 0]]
0.0799846763268
[[ 0.39996169]]
-------------
-------------
[[0 1]]
0.1001276318
[[ 0.5525011]]
-------------
-------------
[[1 1]]
0.165168927065
[[ 0.57475025]]
-------------
-------------
[[0 1]]
0.103412673927
[[ 0.54521945]]
-------------
-------------
[[1 1]]
0.160605072278
[[ 0.56675404]]
-------------
-------------
[[1 0]]
0.103785978618
[[ 0.54439934]]
-------------
-------------
[[1 0]]
0.0948361480812
[[ 0.56448617]]
-------------
-------------
[[0 1]]
0.0897562405976
[[ 0.57631087]]
-------------
-------------
[[1 0]]
0.0793742802969
[[ 0.60156737]]
-------------
-------------
[[1 0]]
0.0725294548194
[[ 0.619134]]
-------------
-------------
[[1 1]]
0.201165165958
[[ 0.63429515]]
-------------
-------------
[[1 0]]
0.0774201470773
[[ 0.60650249]]
-------------
------

-------------
-------------
[[0 0]]
0.0483826069993
[[ 0.31107108]]
-------------
-------------
[[1 1]]
0.102584622314
[[ 0.45295612]]
-------------
-------------
[[1 1]]
0.0925985569154
[[ 0.43034534]]
-------------
-------------
[[1 1]]
0.0835837527435
[[ 0.40886123]]
-------------
-------------
[[0 0]]
0.0306455149091
[[ 0.24757025]]
-------------
-------------
[[1 0]]
0.17965756034
[[ 0.400571]]
-------------
-------------
[[1 0]]
0.164155443202
[[ 0.42701581]]
-------------
-------------
[[1 0]]
0.149991946827
[[ 0.45229215]]
-------------
-------------
[[1 1]]
0.104676452243
[[ 0.45755099]]
-------------
-------------
[[0 1]]
0.15770188436
[[ 0.4383918]]
-------------
-------------
[[0 0]]
0.047602561557
[[ 0.30855327]]
-------------
-------------
[[0 1]]
0.150695330847
[[ 0.45100942]]
-------------
-------------
[[0 0]]
0.0507561923301
[[ 0.31861008]]
-------------
-------------
[[0 0]]
0.047252158952
[[ 0.30741555]]
-------------
-------------
[[1 0]]
0.142348217063
[[ 0.466430

-------------
-------------
[[1 0]]
0.076281018027
[[ 0.6094081]]
-------------
-------------
[[1 0]]
0.0696981978019
[[ 0.62664173]]
-------------
-------------
[[1 1]]
0.194827795858
[[ 0.62422399]]
-------------
-------------
[[1 1]]
0.175871601322
[[ 0.59307942]]
-------------
-------------
[[0 1]]
0.0982140555841
[[ 0.55679789]]
-------------
-------------
[[0 1]]
0.0899331754222
[[ 0.57589347]]
-------------
-------------
[[0 0]]
0.0936200177119
[[ 0.43271242]]
-------------
-------------
[[1 0]]
0.0773214217651
[[ 0.60675346]]
-------------
-------------
[[1 1]]
0.182365530126
[[ 0.60392968]]
-------------
-------------
[[0 0]]
0.0833272178011
[[ 0.40823331]]
-------------
-------------
[[0 1]]
0.100614147861
[[ 0.55141523]]
-------------
-------------
[[0 0]]
0.0844468363886
[[ 0.41096675]]
-------------
-------------
[[1 1]]
0.157868155149
[[ 0.56190418]]
-------------
-------------
[[0 0]]
0.0698114682521
[[ 0.37366153]]
-------------
-------------
[[1 0]]
0.104237616901
[[ 0

0.048923486099
[[ 0.31280501]]
-------------
-------------
[[1 0]]
0.134642709526
[[ 0.48107282]]
-------------
-------------
[[1 1]]
0.112893699575
[[ 0.47517092]]
-------------
-------------
[[0 0]]
0.0458052446565
[[ 0.30267225]]
-------------
-------------
[[0 0]]
0.0426404114691
[[ 0.2920288]]
-------------
-------------
[[1 0]]
0.146224519521
[[ 0.45921442]]
-------------
-------------
[[0 1]]
0.149069607867
[[ 0.45397874]]
-------------
-------------
[[0 0]]
0.0523627769007
[[ 0.32361328]]
-------------
-------------
[[0 1]]
0.142900348984
[[ 0.46539669]]
-------------
-------------
[[0 1]]
0.130840685106
[[ 0.48845199]]
-------------
-------------
[[0 0]]
0.0619864177475
[[ 0.35209776]]
-------------
-------------
[[1 0]]
0.113011352365
[[ 0.52458155]]
-------------
-------------
[[0 0]]
0.0641596607923
[[ 0.35821686]]
-------------
-------------
[[0 0]]
0.0597260910471
[[ 0.34561855]]
-------------
-------------
[[1 1]]
0.12138222427
[[ 0.49271132]]
-------------
-------------

[[ 0.56373599]]
-------------
-------------
[[1 1]]
0.151861534905
[[ 0.55111076]]
-------------
-------------
[[0 0]]
0.0670018547692
[[ 0.36606517]]
-------------
-------------
[[1 0]]
0.104223395033
[[ 0.54344027]]
-------------
-------------
[[0 1]]
0.112104985457
[[ 0.52649185]]
-------------
-------------
[[0 0]]
0.0756655154436
[[ 0.38901289]]
-------------
-------------
[[1 1]]
0.143832925987
[[ 0.5363449]]
-------------
-------------
[[1 0]]
0.104023530059
[[ 0.54387824]]
-------------
-------------
[[1 1]]
0.140714796297
[[ 0.53049938]]
-------------
-------------
[[0 1]]
0.123818049926
[[ 0.50236951]]
-------------
-------------
[[0 1]]
0.11335681001
[[ 0.52385546]]
-------------
-------------
[[0 0]]
0.074814834539
[[ 0.38681994]]
-------------
-------------
[[0 1]]
0.110494340988
[[ 0.52990567]]
-------------
-------------
[[0 1]]
0.101158531705
[[ 0.55020331]]
-------------
-------------
[[0 0]]
0.0833483522828
[[ 0.40828508]]
-------------
-------------
[[0 1]]
0.0993194

0.172451861432
[[ 0.41271496]]
-------------
-------------
[[0 0]]
0.0345356373506
[[ 0.26281414]]
-------------
-------------
[[1 0]]
0.163228390386
[[ 0.42863603]]
-------------
-------------
[[0 1]]
0.168409990699
[[ 0.41963806]]
-------------
-------------
[[0 0]]
0.0443910240926
[[ 0.29796317]]
-------------
-------------
[[1 1]]
0.0902799268239
[[ 0.42492335]]
-------------
-------------
[[1 0]]
0.152715502842
[[ 0.44734187]]
-------------
-------------
[[1 1]]
0.0920509366139
[[ 0.42907094]]
-------------
-------------
[[1 0]]
0.150235892112
[[ 0.45184693]]
-------------
-------------
[[0 0]]
0.0436909951384
[[ 0.29560445]]
-------------
-------------
[[1 0]]
0.143229530511
[[ 0.4647813]]
-------------
-------------
[[1 1]]
0.0993270458609
[[ 0.44570628]]
-------------
-------------
[[0 1]]
0.161462096446
[[ 0.43173581]]
-------------
-------------
[[1 1]]
0.100968382099
[[ 0.44937375]]
-------------
-------------
[[1 0]]
0.139957206343
[[ 0.47093062]]
-------------
------------

[[0 1]]
0.0788000468315
[[ 0.60301122]]
-------------
-------------
[[0 1]]
0.0721288880414
[[ 0.62018718]]
-------------
-------------
[[1 0]]
0.0521440473572
[[ 0.67706333]]
-------------
-------------
[[0 1]]
0.0611363255466
[[ 0.65032493]]
-------------
-------------
[[1 1]]
0.227465337554
[[ 0.67448549]]
-------------
-------------
[[0 0]]
0.108428064824
[[ 0.46567814]]
-------------
-------------
[[1 1]]
0.193731041438
[[ 0.62246452]]
-------------
-------------
[[1 1]]
0.174879450274
[[ 0.59140418]]
-------------
-------------
[[0 1]]
0.0965267795311
[[ 0.56062139]]
-------------
-------------
[[0 0]]
0.0868100695327
[[ 0.4166775]]
-------------
-------------
[[0 1]]
0.0950532687486
[[ 0.56398792]]
-------------
-------------
[[0 0]]
0.0876310699251
[[ 0.41864321]]
-------------
-------------
[[0 0]]
0.0815655757755
[[ 0.40389498]]
-------------
-------------
[[1 0]]
0.0838928055003
[[ 0.59038358]]
-------------
-------------
[[0 1]]
0.0927276747271
[[ 0.56935473]]
-------------

0.0724704811726
[[ 0.38071113]]
-------------
-------------
[[0 0]]
0.0674526521294
[[ 0.36729457]]
-------------
-------------
[[1 0]]
0.0963634862247
[[ 0.5609932]]
-------------
-------------
[[0 0]]
0.0689882227923
[[ 0.37145181]]
-------------
-------------
[[0 1]]
0.114350500303
[[ 0.52177307]]
-------------
-------------
[[0 1]]
0.104660953309
[[ 0.54248289]]
-------------
-------------
[[0 0]]
0.0776555229234
[[ 0.39409522]]
-------------
-------------
[[1 1]]
0.151986337871
[[ 0.55133717]]
-------------
-------------
[[0 0]]
0.0640077157677
[[ 0.35779244]]
-------------
-------------
[[0 0]]
0.0595761348336
[[ 0.3451844]]
-------------
-------------
[[0 0]]
0.0554515302368
[[ 0.33302111]]
-------------
-------------
[[1 0]]
0.112532980294
[[ 0.52558883]]
-------------
-------------
[[1 0]]
0.102799033201
[[ 0.54657077]]
-------------
-------------
[[0 0]]
0.06387700102
[[ 0.35742692]]
-------------
-------------
[[0 1]]
0.120515667679
[[ 0.50905058]]
-------------
------------

-------------
[[0 1]]
0.0953804934904
[[ 0.56323807]]
-------------
-------------
[[1 0]]
0.0690440893905
[[ 0.62839782]]
-------------
-------------
[[1 0]]
0.0630690178806
[[ 0.64484083]]
-------------
-------------
[[0 0]]
0.097305817032
[[ 0.44114809]]
-------------
-------------
[[0 1]]
0.081418703477
[[ 0.59646883]]
-------------
-------------
[[0 0]]
0.0972444866837
[[ 0.44100904]]
-------------
-------------
[[0 0]]
0.0905059489665
[[ 0.42545493]]
-------------
-------------
[[1 0]]
0.069321021517
[[ 0.62765333]]
-------------
-------------
[[1 0]]
0.0633223460676
[[ 0.64412826]]
-------------
-------------
[[1 0]]
0.0578429153692
[[ 0.6598738]]
-------------
-------------
[[1 1]]
0.201189679996
[[ 0.63433379]]
-------------
-------------
[[1 1]]
0.181617183062
[[ 0.60268928]]
-------------
-------------
[[0 0]]
0.0807189295378
[[ 0.4017933]]
-------------
-------------
[[1 0]]
0.0791505241336
[[ 0.60212936]]
-------------
-------------
[[1 0]]
0.0723007168887
[[ 0.61973505]]
-

-------------
-------------
[[1 1]]
0.234554694121
[[ 0.68491561]]
-------------
-------------
[[1 1]]
0.211737964423
[[ 0.65075028]]
-------------
-------------
[[0 0]]
0.0953131070127
[[ 0.43660762]]
-------------
-------------
[[1 0]]
0.0640875445583
[[ 0.64198451]]
-------------
-------------
[[0 0]]
0.0946797691733
[[ 0.43515461]]
-------------
-------------
[[1 1]]
0.180205591121
[[ 0.60034255]]
-------------
-------------
[[1 0]]
0.0747647292583
[[ 0.61330961]]
-------------
-------------
[[0 1]]
0.0849919223971
[[ 0.58770903]]
-------------
-------------
[[1 0]]
0.0619788605223
[[ 0.6479237]]
-------------
-------------
[[0 0]]
0.0967802676689
[[ 0.43995515]]
-------------
-------------
[[0 0]]
0.0900699276361
[[ 0.42442886]]
-------------
-------------
[[1 1]]
0.173490555785
[[ 0.58905103]]
-------------
-------------
[[1 0]]
0.0787691558992
[[ 0.60308904]]
-------------
-------------
[[1 1]]
0.166971810367
[[ 0.57787855]]
-------------
-------------
[[1 1]]
0.150723151646
[[ 

-------------
[[1 1]]
0.130338196652
[[ 0.51056478]]
-------------
-------------
[[1 1]]
0.117648115246
[[ 0.48507343]]
-------------
-------------
[[1 1]]
0.106191648028
[[ 0.46085062]]
-------------
-------------
[[1 0]]
0.127640591729
[[ 0.49474642]]
-------------
-------------
[[0 0]]
0.0468237203411
[[ 0.30601869]]
-------------
-------------
[[1 0]]
0.122299686778
[[ 0.50543011]]
-------------
-------------
[[1 0]]
0.111699109434
[[ 0.52734979]]
-------------
-------------
[[0 0]]
0.0554223828004
[[ 0.33293358]]
-------------
-------------
[[1 1]]
0.11533598221
[[ 0.48028321]]
-------------
-------------
[[1 1]]
0.104104476227
[[ 0.45629919]]
-------------
-------------
[[0 0]]
0.0400727864798
[[ 0.28309993]]
-------------
-------------
[[0 0]]
0.0372936076234
[[ 0.2731066]]
-------------
-------------
[[1 0]]
0.14005515104
[[ 0.47074552]]
-------------
-------------
[[1 0]]
0.12791405969
[[ 0.49420546]]
-------------
-------------
[[1 0]]
0.116826686047
[[ 0.51662295]]
---------

[[0 1]]
0.112373484816
[[ 0.52592514]]
-------------
-------------
[[1 0]]
0.0842120813054
[[ 0.58960487]]
-------------
-------------
[[0 0]]
0.0756460221988
[[ 0.38896278]]
-------------
-------------
[[1 1]]
0.144967806802
[[ 0.5384567]]
-------------
-------------
[[1 0]]
0.093363102052
[[ 0.56788172]]
-------------
-------------
[[1 1]]
0.141205411286
[[ 0.53142339]]
-------------
-------------
[[1 1]]
0.127451572138
[[ 0.50487934]]
-------------
-------------
[[0 0]]
0.0538059786761
[[ 0.32804262]]
-------------
-------------
[[1 0]]
0.112192626982
[[ 0.52630679]]
-------------
-------------
[[0 1]]
0.123716590389
[[ 0.50257344]]
-------------
-------------
[[1 1]]
0.130694020616
[[ 0.51126123]]
-------------
-------------
[[1 0]]
0.10365101431
[[ 0.54469567]]
-------------
-------------
[[1 1]]
0.128347196333
[[ 0.50665017]]
-------------
-------------
[[0 0]]
0.0545671263434
[[ 0.33035474]]
-------------
-------------
[[0 0]]
0.0507792629789
[[ 0.31868248]]
-------------
------

[[0 0]]
0.0540022799734
[[ 0.32864047]]
-------------
-------------
[[0 0]]
0.0502511741855
[[ 0.31702105]]
-------------
-------------
[[1 0]]
0.115411352732
[[ 0.51955988]]
-------------
-------------
[[0 1]]
0.127451139539
[[ 0.49512152]]
-------------
-------------
[[0 1]]
0.1165851929
[[ 0.5171228]]
-------------
-------------
[[1 1]]
0.136962623188
[[ 0.52337868]]
-------------
-------------
[[0 1]]
0.118158577534
[[ 0.51387537]]
-------------
-------------
[[1 0]]
0.0885158373523
[[ 0.57924868]]
-------------
-------------
[[0 0]]
0.070755764365
[[ 0.37618018]]
-------------
-------------
[[0 1]]
0.106343612415
[[ 0.53881975]]
-------------
-------------
[[0 1]]
0.0972776797665
[[ 0.5589157]]
-------------
-------------
[[0 0]]
0.0789824131701
[[ 0.39744789]]
-------------
-------------
[[0 0]]
0.0734951053225
[[ 0.38339302]]
-------------
-------------
[[1 1]]
0.142860220331
[[ 0.53452824]]
-------------
-------------
[[0 1]]
0.113326209235
[[ 0.52391974]]
-------------
-------

[[1 1]]
0.0996479165915
[[ 0.44642562]]
-------------
-------------
[[1 0]]
0.132785605932
[[ 0.48466398]]
-------------
-------------
[[1 0]]
0.121246775277
[[ 0.50756366]]
-------------
-------------
[[1 0]]
0.110712030486
[[ 0.52944282]]
-------------
-------------
[[1 1]]
0.121095115899
[[ 0.49212827]]
-------------
-------------
[[0 0]]
0.048389472486
[[ 0.31109315]]
-------------
-------------
[[0 1]]
0.135826548893
[[ 0.47879649]]
-------------
-------------
[[1 1]]
0.114791469185
[[ 0.47914814]]
-------------
-------------
[[0 0]]
0.0451752263221
[[ 0.30058352]]
-------------
-------------
[[0 1]]
0.141535755697
[[ 0.46795535]]
-------------
-------------
[[1 0]]
0.112074523364
[[ 0.52655618]]
-------------
-------------
[[0 0]]
0.054065497422
[[ 0.32883278]]
-------------
-------------
[[1 1]]
0.113544648251
[[ 0.47653887]]
-------------
-------------
[[1 1]]
0.102476559926
[[ 0.45271748]]
-------------
-------------
[[0 1]]
0.148071757039
[[ 0.4558093]]
-------------
--------

[[0 0]]
0.0791909796087
[[ 0.39797231]]
-------------
-------------
[[1 0]]
0.076575126426
[[ 0.60865584]]
-------------
-------------
[[0 1]]
0.0847682728385
[[ 0.58825184]]
-------------
-------------
[[1 0]]
0.0635116437804
[[ 0.64359673]]
-------------
-------------
[[0 1]]
0.0716523429701
[[ 0.62144395]]
-------------
-------------
[[1 0]]
0.0526283474966
[[ 0.67556712]]
-------------
-------------
[[1 1]]
0.200447678046
[[ 0.63316298]]
-------------
-------------
[[1 1]]
0.180914511652
[[ 0.60152226]]
-------------
-------------
[[1 1]]
0.163281110968
[[ 0.57145623]]
-------------
-------------
[[0 1]]
0.09334918258
[[ 0.56791394]]
-------------
-------------
[[1 0]]
0.0705579697514
[[ 0.62434598]]
-------------
-------------
[[1 1]]
0.168197300041
[[ 0.57999534]]
-------------
-------------
[[1 0]]
0.0744779511286
[[ 0.61405194]]
-------------
-------------
[[1 1]]
0.161746235755
[[ 0.56876399]]
-------------
-------------
[[0 1]]
0.0942139515738
[[ 0.56591717]]
-------------
--

-------------
-------------
[[1 0]]
0.0540892194214
[[ 0.67109509]]
-------------
-------------
[[1 0]]
0.0493851167915
[[ 0.68572268]]
-------------
-------------
[[0 1]]
0.0603181053608
[[ 0.65267276]]
-------------
-------------
[[1 1]]
0.211242960559
[[ 0.64998917]]
-------------
-------------
[[1 0]]
0.0498470454119
[[ 0.68425629]]
-------------
-------------
[[0 0]]
0.104911961185
[[ 0.45806541]]
-------------
-------------
[[1 1]]
0.188478345489
[[ 0.61396799]]
-------------
-------------
[[1 0]]
0.0604968490194
[[ 0.65215852]]
-------------
-------------
[[1 0]]
0.0552348605412
[[ 0.66763014]]
-------------
-------------
[[1 1]]
0.188856343204
[[ 0.61458334]]
-------------
-------------
[[0 0]]
0.0875570306749
[[ 0.41846632]]
-------------
-------------
[[1 0]]
0.0656084065521
[[ 0.63776139]]
-------------
-------------
[[1 1]]
0.170544429325
[[ 0.58402813]]
-------------
-------------
[[0 1]]
0.0889054759901
[[ 0.57832364]]
-------------
-------------
[[0 0]]
0.0841457859783
[

[[ 0.32682467]]
-------------
-------------
[[1 1]]
0.101621266036
[[ 0.45082428]]
-------------
-------------
[[1 0]]
0.117619117256
[[ 0.51498636]]
-------------
-------------
[[1 0]]
0.107369723128
[[ 0.53660012]]
-------------
-------------
[[0 1]]
0.12186848662
[[ 0.50630275]]
-------------
-------------
[[1 1]]
0.12234481654
[[ 0.49466113]]
-------------
-------------
[[1 1]]
0.11040066712
[[ 0.46989502]]
-------------
-------------
[[0 0]]
0.0492088942197
[[ 0.3137161]]
-------------
-------------
[[0 1]]
0.139824961229
[[ 0.47118063]]
-------------
-------------
[[0 0]]
0.0521357528389
[[ 0.32291099]]
-------------
-------------
[[0 0]]
0.0485031825056
[[ 0.31145845]]
-------------
-------------
[[1 0]]
0.115413349235
[[ 0.51955573]]
-------------
-------------
[[0 1]]
0.129570393449
[[ 0.49094127]]
-------------
-------------
[[1 0]]
0.0956171616885
[[ 0.56269653]]
-------------
-------------
[[1 1]]
0.124480012733
[[ 0.49895894]]
-------------
-------------
[[0 1]]
0.12068021

-------------
[[1 0]]
0.0882060042949
[[ 0.5799857]]
-------------
-------------
[[1 0]]
0.0805199642037
[[ 0.59870219]]
-------------
-------------
[[1 1]]
0.142300456001
[[ 0.53348]]
-------------
-------------
[[0 0]]
0.0631172148305
[[ 0.35529485]]
-------------
-------------
[[1 1]]
0.121409409795
[[ 0.4927665]]
-------------
-------------
[[0 1]]
0.123709039071
[[ 0.50258862]]
-------------
-------------
[[0 1]]
0.113096524864
[[ 0.52440243]]
-------------
-------------
[[0 1]]
0.103395223342
[[ 0.54525782]]
-------------
-------------
[[0 1]]
0.0945267426467
[[ 0.56519719]]
-------------
-------------
[[1 1]]
0.153302930607
[[ 0.55372002]]
-------------
-------------
[[0 0]]
0.069090721032
[[ 0.37172765]]
-------------
-------------
[[1 0]]
0.0821756339368
[[ 0.5945974]]
-------------
-------------
[[1 0]]
0.0750148615982
[[ 0.61266329]]
-------------
-------------
[[1 1]]
0.15008564542
[[ 0.5478789]]
-------------
-------------
[[1 1]]
0.13543926034
[[ 0.52045991]]
------------

[[ 0.57511943]]
-------------
-------------
[[1 0]]
0.0608885634788
[[ 0.6510342]]
-------------
-------------
[[0 0]]
0.0875504478615
[[ 0.41845059]]
-------------
-------------
[[0 0]]
0.0814408572551
[[ 0.40358607]]
-------------
-------------
[[0 1]]
0.0891944833819
[[ 0.57763882]]
-------------
-------------
[[0 1]]
0.0815352371007
[[ 0.59618015]]
-------------
-------------
[[1 0]]
0.0543381054475
[[ 0.67033925]]
-------------
-------------
[[0 1]]
0.0691884111598
[[ 0.62800965]]
-------------
-------------
[[0 1]]
0.0632479692469
[[ 0.64433732]]
-------------
-------------
[[1 1]]
0.199768082343
[[ 0.63208873]]
-------------
-------------
[[1 1]]
0.180277915515
[[ 0.60046301]]
-------------
-------------
[[0 0]]
0.0847917419204
[[ 0.41180515]]
-------------
-------------
[[0 0]]
0.0788745261672
[[ 0.39717635]]
-------------
-------------
[[0 1]]
0.0915982948198
[[ 0.57198529]]
-------------
-------------
[[0 1]]
0.0837321998437
[[ 0.59077586]]
-------------
-------------
[[1 1]]

-------------
[[1 1]]
0.138459925408
[[ 0.52623175]]
-------------
-------------
[[0 0]]
0.0618145150612
[[ 0.3516092]]
-------------
-------------
[[1 1]]
0.118098013646
[[ 0.48600003]]
-------------
-------------
[[1 0]]
0.0976595310927
[[ 0.55805084]]
-------------
-------------
[[0 1]]
0.113184698151
[[ 0.52421707]]
-------------
-------------
[[0 0]]
0.0629978366761
[[ 0.35495869]]
-------------
-------------
[[0 1]]
0.109645633241
[[ 0.53171455]]
-------------
-------------
[[1 1]]
0.130820979867
[[ 0.51150949]]
-------------
-------------
[[0 0]]
0.057653117741
[[ 0.33956772]]
-------------
-------------
[[1 0]]
0.0934711099593
[[ 0.56763185]]
-------------
-------------
[[0 1]]
0.108514623115
[[ 0.53413602]]
-------------
-------------
[[1 1]]
0.132040526354
[[ 0.51388817]]
-------------
-------------
[[1 1]]
0.119139856068
[[ 0.48813903]]
-------------
-------------
[[0 1]]
0.121082027601
[[ 0.50789833]]
-------------
-------------
[[1 1]]
0.118261966568
[[ 0.48633726]]
------

-------------
-------------
[[1 1]]
0.159604502053
[[ 0.56498584]]
-------------
-------------
[[1 1]]
0.14400870021
[[ 0.53667253]]
-------------
-------------
[[0 0]]
0.0645001516142
[[ 0.35916612]]
-------------
-------------
[[1 1]]
0.122812058584
[[ 0.4956048]]
-------------
-------------
[[0 0]]
0.0532164614726
[[ 0.32624059]]
-------------
-------------
[[0 0]]
0.0494973967055
[[ 0.31463438]]
-------------
-------------
[[1 1]]
0.0992227586773
[[ 0.44547224]]
-------------
-------------
[[0 1]]
0.137072929573
[[ 0.4764106]]
-------------
-------------
[[1 1]]
0.100020721513
[[ 0.44725993]]
-------------
-------------
[[0 0]]
0.0412711910516
[[ 0.2873019]]
-------------
-------------
[[0 0]]
0.0383870130387
[[ 0.27708126]]
-------------
-------------
[[0 0]]
0.0357044489369
[[ 0.26722443]]
-------------
-------------
[[0 1]]
0.152833986608
[[ 0.44712753]]
-------------
-------------
[[0 1]]
0.139671387392
[[ 0.47147112]]
-------------
-------------
[[0 1]]
0.12764413228
[[ 0.4947

[[ 0.34782637]]
-------------
-------------
[[0 0]]
0.0562600613895
[[ 0.33544019]]
-------------
-------------
[[1 1]]
0.109754878975
[[ 0.46851868]]
-------------
-------------
[[1 1]]
0.0990124190387
[[ 0.44499982]]
-------------
-------------
[[1 0]]
0.114374768104
[[ 0.52172232]]
-------------
-------------
[[1 1]]
0.0989127570865
[[ 0.4447758]]
-------------
-------------
[[1 0]]
0.11407596152
[[ 0.52234749]]
-------------
-------------
[[0 0]]
0.0467344504042
[[ 0.30572684]]
-------------
-------------
[[0 1]]
0.128523601201
[[ 0.49300177]]
-------------
-------------
[[1 0]]
0.0995861073431
[[ 0.55371286]]
-------------
-------------
[[1 0]]
0.0908684813404
[[ 0.57369382]]
-------------
-------------
[[1 0]]
0.0829153334011
[[ 0.59277688]]
-------------
-------------
[[1 1]]
0.132626508358
[[ 0.5150272]]
-------------
-------------
[[1 1]]
0.119650197094
[[ 0.4891834]]
-------------
-------------
[[0 1]]
0.113584800588
[[ 0.52337688]]
-------------
-------------
[[0 0]]
0.05850

-------------
-------------
[[1 1]]
0.101717738495
[[ 0.45103822]]
-------------
-------------
[[1 0]]
0.110103869567
[[ 0.53073703]]
-------------
-------------
[[0 1]]
0.11846428394
[[ 0.51324691]]
-------------
-------------
[[1 0]]
0.0913177589844
[[ 0.57264123]]
-------------
-------------
[[1 1]]
0.121194974427
[[ 0.49233114]]
-------------
-------------
[[0 0]]
0.0520152693073
[[ 0.32253765]]
-------------
-------------
[[1 0]]
0.0984040560945
[[ 0.5563694]]
-------------
-------------
[[1 0]]
0.0897823197833
[[ 0.57624932]]
-------------
-------------
[[1 1]]
0.122517660581
[[ 0.49501043]]
-------------
-------------
[[1 1]]
0.110522562027
[[ 0.47015436]]
-------------
-------------
[[0 0]]
0.0467588856401
[[ 0.30580675]]
-------------
-------------
[[1 1]]
0.0943851284548
[[ 0.43447699]]
-------------
-------------
[[1 0]]
0.116151124192
[[ 0.51802256]]
-------------
-------------
[[1 0]]
0.105970524851
[[ 0.53962944]]
-------------
-------------
[[1 1]]
0.104083933869
[[ 0.45

[[0 1]]
0.113746792946
[[ 0.52303712]]
-------------
-------------
[[0 0]]
0.0556523376266
[[ 0.33362355]]
-------------
-------------
[[0 1]]
0.109757293502
[[ 0.53147616]]
-------------
-------------
[[0 0]]
0.0577286191325
[[ 0.33978999]]
-------------
-------------
[[1 1]]
0.111467296913
[[ 0.4721595]]
-------------
-------------
[[0 1]]
0.116536424632
[[ 0.51722381]]
-------------
-------------
[[1 0]]
0.0894256105067
[[ 0.57709195]]
-------------
-------------
[[1 1]]
0.120202964146
[[ 0.49031207]]
-------------
-------------
[[0 0]]
0.0524061556167
[[ 0.3237473]]
-------------
-------------
[[0 0]]
0.0487336102703
[[ 0.31219741]]
-------------
-------------
[[1 0]]
0.101855221062
[[ 0.54865707]]
-------------
-------------
[[1 1]]
0.106484716174
[[ 0.46148611]]
-------------
-------------
[[0 0]]
0.0449999348469
[[ 0.29999978]]
-------------
-------------
[[0 1]]
0.126928768551
[[ 0.49615723]]
-------------
-------------
[[1 1]]
0.101131791851
[[ 0.44973724]]
-------------
-----

-------------
[[1 0]]
0.131405331887
[[ 0.48734937]]
-------------
-------------
[[1 0]]
0.119861991112
[[ 0.51038384]]
-------------
-------------
[[0 1]]
0.130668276053
[[ 0.48878913]]
-------------
-------------
[[1 0]]
0.0993098654161
[[ 0.55433226]]
-------------
-------------
[[0 0]]
0.0502092332492
[[ 0.31688873]]
-------------
-------------
[[1 1]]
0.100616737992
[[ 0.44859054]]
-------------
-------------
[[1 0]]
0.105272134573
[[ 0.54114897]]
-------------
-------------
[[0 1]]
0.116497834386
[[ 0.51730375]]
-------------
-------------
[[0 0]]
0.0524765381296
[[ 0.32396462]]
-------------
-------------
[[0 0]]
0.0487962835647
[[ 0.31239809]]
-------------
-------------
[[1 1]]
0.098796390168
[[ 0.44451409]]
-------------
-------------
[[1 1]]
0.0891071292592
[[ 0.42215431]]
-------------
-------------
[[0 0]]
0.0353833715605
[[ 0.26602019]]
-------------
-------------
[[1 0]]
0.121435403855
[[ 0.50718076]]
-------------
-------------
[[1 0]]
0.110770356639
[[ 0.52931888]]
---

-------------
-------------
[[0 0]]
0.0593755929898
[[ 0.34460294]]
-------------
-------------
[[0 0]]
0.0552080353377
[[ 0.33228914]]
-------------
-------------
[[1 1]]
0.113092870761
[[ 0.47558989]]
-------------
-------------
[[1 1]]
0.102000902754
[[ 0.45166559]]
-------------
-------------
[[1 0]]
0.103640391967
[[ 0.54471901]]
-------------
-------------
[[0 0]]
0.0451842950667
[[ 0.30061369]]
-------------
-------------
[[0 1]]
0.118888195263
[[ 0.51237679]]
-------------
-------------
[[0 1]]
0.108589491066
[[ 0.53397534]]
-------------
-------------
[[0 1]]
0.0991844422782
[[ 0.55461378]]
-------------
-------------
[[0 1]]
0.0905952628385
[[ 0.5743352]]
-------------
-------------
[[1 0]]
0.0677130062444
[[ 0.63199727]]
-------------
-------------
[[1 0]]
0.0617674674342
[[ 0.64852463]]
-------------
-------------
[[1 1]]
0.154513841878
[[ 0.55590258]]
-------------
-------------
[[0 1]]
0.0807571485915
[[ 0.59811159]]
-------------
-------------
[[0 1]]
0.0737652335322
[[ 

-------------
-------------
[[0 1]]
0.105635318997
[[ 0.54035814]]
-------------
-------------
[[0 1]]
0.0964749199367
[[ 0.56073944]]
-------------
-------------
[[1 0]]
0.0729485437736
[[ 0.61803523]]
-------------
-------------
[[0 0]]
0.0650005672127
[[ 0.3605567]]
-------------
-------------
[[1 0]]
0.0716922683473
[[ 0.62133849]]
-------------
-------------
[[1 0]]
0.0653894633518
[[ 0.63836631]]
-------------
-------------
[[1 0]]
0.0596417564474
[[ 0.65462555]]
-------------
-------------
[[0 1]]
0.0685586861339
[[ 0.62970637]]
-------------
-------------
[[0 0]]
0.0818250021709
[[ 0.40453678]]
-------------
-------------
[[0 0]]
0.0760753565967
[[ 0.39006501]]
-------------
-------------
[[0 1]]
0.0737309154951
[[ 0.61599241]]
-------------
-------------
[[1 0]]
0.0537948808746
[[ 0.67199122]]
-------------
-------------
[[0 1]]
0.0622616693561
[[ 0.64712135]]
-------------
-------------
[[1 1]]
0.174942808973
[[ 0.5915113]]
-------------
-------------
[[1 1]]
0.157793047861
[

[[1 1]]
0.0831789470172
[[ 0.40786995]]
-------------
-------------
[[0 1]]
0.138318654353
[[ 0.47403678]]
-------------
-------------
[[1 1]]
0.084743473451
[[ 0.41168792]]
-------------
-------------
[[0 1]]
0.136196079071
[[ 0.47808798]]
-------------
-------------
[[0 0]]
0.0361355687167
[[ 0.26883292]]
-------------
-------------
[[1 1]]
0.081823425402
[[ 0.40453288]]
-------------
-------------
[[0 0]]
0.0294703010845
[[ 0.24277686]]
-------------
-------------
[[1 1]]
0.0701490423937
[[ 0.37456386]]
-------------
-------------
[[1 1]]
0.0632491203084
[[ 0.35566591]]
-------------
-------------
[[0 0]]
0.0208927351273
[[ 0.20441495]]
-------------
-------------
[[0 1]]
0.167708119443
[[ 0.42084869]]
-------------
-------------
[[1 0]]
0.132837828057
[[ 0.48456266]]
-------------
-------------
[[1 1]]
0.0723808608851
[[ 0.38047565]]
-------------
-------------
[[0 0]]
0.0251469510149
[[ 0.22426302]]
-------------
-------------
[[1 1]]
0.0621070532421
[[ 0.35244022]]
-------------


-------------
-------------
[[1 0]]
0.0659265964775
[[ 0.63688405]]
-------------
-------------
[[0 0]]
0.0660008318601
[[ 0.36332033]]
-------------
-------------
[[1 1]]
0.129686527819
[[ 0.50928681]]
-------------
-------------
[[0 1]]
0.0932786437322
[[ 0.56807722]]
-------------
-------------
[[1 0]]
0.0669923667479
[[ 0.63396075]]
-------------
-------------
[[0 1]]
0.0787823717532
[[ 0.60305574]]
-------------
-------------
[[1 1]]
0.145277254375
[[ 0.53903108]]
-------------
-------------
[[0 1]]
0.0818443837881
[[ 0.59541531]]
-------------
-------------
[[0 0]]
0.0683694464896
[[ 0.36978222]]
-------------
-------------
[[1 0]]
0.0628580299143
[[ 0.64543539]]
-------------
-------------
[[1 1]]
0.141787869161
[[ 0.5325183]]
-------------
-------------
[[1 0]]
0.0660904849488
[[ 0.63643299]]
-------------
-------------
[[1 1]]
0.136532127952
[[ 0.52255551]]
-------------
-------------
[[1 1]]
0.123114009617
[[ 0.49621368]]
-------------
-------------
[[1 1]]
0.111010000345
[[ 

0.148277092022
[[ 0.45543211]]
-------------
-------------
[[0 1]]
0.162013399087
[[ 0.43076648]]
-------------
-------------
[[1 0]]
0.12270667962
[[ 0.50460787]]
-------------
-------------
[[0 1]]
0.136481915628
[[ 0.47754059]]
-------------
-------------
[[1 1]]
0.0823405582544
[[ 0.40580921]]
-------------
-------------
[[0 0]]
0.0314818480913
[[ 0.25092568]]
-------------
-------------
[[0 0]]
0.029263199312
[[ 0.2419223]]
-------------
-------------
[[0 0]]
0.0272009399627
[[ 0.23324211]]
-------------
-------------
[[0 0]]
0.0252840410457
[[ 0.22487348]]
-------------
-------------
[[0 0]]
0.0235022521745
[[ 0.21680522]]
-------------
-------------
[[0 1]]
0.158266083195
[[ 0.43738809]]
-------------
-------------
[[1 1]]
0.0667715063398
[[ 0.36543537]]
-------------
-------------
[[0 1]]
0.153855847325
[[ 0.44528233]]
-------------
-------------
[[0 0]]
0.0281813920259
[[ 0.23740848]]
-------------
-------------
[[0 0]]
0.0261953939692
[[ 0.22889034]]
-------------
-----------

-------------
-------------
[[0 1]]
0.0661185109434
[[ 0.63635591]]
-------------
-------------
[[1 0]]
0.0444330737137
[[ 0.70189574]]
-------------
-------------
[[0 1]]
0.0559729042534
[[ 0.66541696]]
-------------
-------------
[[0 0]]
0.0877949003131
[[ 0.41903437]]
-------------
-------------
[[1 1]]
0.16598244414
[[ 0.57616394]]
-------------
-------------
[[0 1]]
0.0657554549769
[[ 0.63735567]]
-------------
-------------
[[0 0]]
0.0778722015219
[[ 0.39464465]]
-------------
-------------
[[0 0]]
0.0723786558042
[[ 0.38046986]]
-------------
-------------
[[0 1]]
0.0706562828631
[[ 0.62408436]]
-------------
-------------
[[0 0]]
0.0727089521814
[[ 0.381337]]
-------------
-------------
[[1 0]]
0.0531788112568
[[ 0.67387484]]
-------------
-------------
[[0 1]]
0.0646471231321
[[ 0.64042491]]
-------------
-------------
[[1 1]]
0.161152967833
[[ 0.56771994]]
-------------
-------------
[[1 0]]
0.0520240580142
[[ 0.6774351]]
-------------
-------------
[[1 1]]
0.153493304224
[[ 

[[ 0.63883322]]
-------------
-------------
[[1 1]]
0.157734300632
[[ 0.56166592]]
-------------
-------------
[[1 1]]
0.142211150835
[[ 0.53331257]]
-------------
-------------
[[0 1]]
0.0786104389868
[[ 0.60348912]]
-------------
-------------
[[1 1]]
0.137705882716
[[ 0.52479688]]
-------------
-------------
[[0 1]]
0.0814027498675
[[ 0.59650836]]
-------------
-------------
[[1 0]]
0.059279940299
[[ 0.65567475]]
-------------
-------------
[[0 0]]
0.0641823553982
[[ 0.35828021]]
-------------
-------------
[[0 0]]
0.0596509090133
[[ 0.34540095]]
-------------
-------------
[[1 1]]
0.127701985867
[[ 0.50537508]]
-------------
-------------
[[0 0]]
0.0488285760635
[[ 0.31250144]]
-------------
-------------
[[1 0]]
0.0766958408954
[[ 0.6083475]]
-------------
-------------
[[0 0]]
0.0501338822284
[[ 0.31665086]]
-------------
-------------
[[0 1]]
0.09162532094
[[ 0.57192215]]
-------------
-------------
[[1 1]]
0.121627749018
[[ 0.49320939]]
-------------
-------------
[[1 0]]
0.076

-------------
[[1 0]]
0.0813283438093
[[ 0.59669281]]
-------------
-------------
[[0 1]]
0.0918270875005
[[ 0.57145108]]
-------------
-------------
[[0 1]]
0.0838012730501
[[ 0.5906071]]
-------------
-------------
[[1 0]]
0.0608481097853
[[ 0.65115015]]
-------------
-------------
[[0 0]]
0.0626359917439
[[ 0.35393782]]
-------------
-------------
[[0 0]]
0.058207912882
[[ 0.34119763]]
-------------
-------------
[[1 1]]
0.120664173326
[[ 0.49125182]]
-------------
-------------
[[1 1]]
0.108757061056
[[ 0.46638409]]
-------------
-------------
[[0 0]]
0.0420732785042
[[ 0.29008026]]
-------------
-------------
[[0 1]]
0.105134072586
[[ 0.54144995]]
-------------
-------------
[[0 0]]
0.044220070431
[[ 0.29738887]]
-------------
-------------
[[0 1]]
0.100957179419
[[ 0.55065118]]
-------------
-------------
[[1 0]]
0.0754155280727
[[ 0.61163026]]
-------------
-------------
[[1 1]]
0.115207418759
[[ 0.48001546]]
-------------
-------------
[[1 1]]
0.103836429891
[[ 0.45571138]]
---

0.0955209089353
[[ 0.56291669]]
-------------
-------------
[[0 1]]
0.0871587711776
[[ 0.58248648]]
-------------
-------------
[[0 0]]
0.0536362421383
[[ 0.32752478]]
-------------
-------------
[[0 1]]
0.0845737292006
[[ 0.5887246]]
-------------
-------------
[[1 1]]
0.120694498531
[[ 0.49131354]]
-------------
-------------
[[0 1]]
0.0865394080161
[[ 0.58397258]]
-------------
-------------
[[0 1]]
0.0789653615756
[[ 0.60259501]]
-------------
-------------
[[1 1]]
0.127160849416
[[ 0.50430318]]
-------------
-------------
[[1 1]]
0.114594916988
[[ 0.47873775]]
-------------
-------------
[[1 0]]
0.0758309450406
[[ 0.61056208]]
-------------
-------------
[[1 0]]
0.0691016027312
[[ 0.62824308]]
-------------
-------------
[[0 1]]
0.0772288764365
[[ 0.60698886]]
-------------
-------------
[[1 0]]
0.0570868878528
[[ 0.6621039]]
-------------
-------------
[[0 0]]
0.06544872419
[[ 0.36179752]]
-------------
-------------
[[1 1]]
0.129964577085
[[ 0.50983248]]
-------------
----------

-------------
[[0 1]]
0.0515044608963
[[ 0.67904997]]
-------------
-------------
[[1 0]]
0.0341301739367
[[ 0.73873319]]
-------------
-------------
[[0 0]]
0.0895952521306
[[ 0.42330899]]
-------------
-------------
[[1 1]]
0.163028722268
[[ 0.5710144]]
-------------
-------------
[[0 1]]
0.0572207575244
[[ 0.66170794]]
-------------
-------------
[[0 1]]
0.0522057396203
[[ 0.67687235]]
-------------
-------------
[[0 0]]
0.0842568227766
[[ 0.41050414]]
-------------
-------------
[[0 1]]
0.0525718999856
[[ 0.67574115]]
-------------
-------------
[[1 0]]
0.0353436613759
[[ 0.73412912]]
-------------
-------------
[[0 1]]
0.044466409552
[[ 0.70178394]]
-------------
-------------
[[1 1]]
0.178904353107
[[ 0.59817113]]
-------------
-------------
[[0 1]]
0.0490047014414
[[ 0.68693547]]
-------------
-------------
[[1 0]]
0.032659257584
[[ 0.74442513]]
-------------
-------------
[[1 0]]
0.0297610348802
[[ 0.75602855]]
-------------
-------------
[[1 1]]
0.183461727986
[[ 0.60574207]]


[[1 0]]
0.0743145978789
[[ 0.61447543]]
-------------
-------------
[[0 1]]
0.0848760084627
[[ 0.58799027]]
-------------
-------------
[[1 1]]
0.115680456533
[[ 0.48099991]]
-------------
-------------
[[0 1]]
0.0866251903729
[[ 0.58376643]]
-------------
-------------
[[0 0]]
0.0502984811703
[[ 0.31717024]]
-------------
-------------
[[0 1]]
0.0838898089185
[[ 0.5903909]]
-------------
-------------
[[1 1]]
0.11647378341
[[ 0.48264642]]
-------------
-------------
[[1 0]]
0.0692489169527
[[ 0.62784703]]
-------------
-------------
[[0 0]]
0.0501389889681
[[ 0.31666698]]
-------------
-------------
[[0 1]]
0.0840226235454
[[ 0.59006678]]
-------------
-------------
[[1 1]]
0.116262564092
[[ 0.48220859]]
-------------
-------------
[[0 1]]
0.0858254099186
[[ 0.58569236]]
-------------
-------------
[[1 1]]
0.11378683667
[[ 0.47704683]]
-------------
-------------
[[1 0]]
0.0710916988258
[[ 0.62292786]]
-------------
-------------
[[1 0]]
0.0647676948293
[[ 0.64008975]]
-------------
-

-------------
[[0 0]]
0.0477071595346
[[ 0.30889208]]
-------------
-------------
[[0 1]]
0.0782613230391
[[ 0.60437057]]
-------------
-------------
[[0 0]]
0.0489987725781
[[ 0.3130456]]
-------------
-------------
[[1 0]]
0.0639275557836
[[ 0.64243167]]
-------------
-------------
[[1 0]]
0.0582375451248
[[ 0.65871553]]
-------------
-------------
[[1 1]]
0.13078259583
[[ 0.51143445]]
-------------
-------------
[[0 0]]
0.0475906829677
[[ 0.30851477]]
-------------
-------------
[[1 1]]
0.112017015982
[[ 0.47332233]]
-------------
-------------
[[0 1]]
0.0872451488241
[[ 0.58227964]]
-------------
-------------
[[0 0]]
0.0433285373603
[[ 0.29437574]]
-------------
-------------
[[1 0]]
0.0712325129005
[[ 0.62255461]]
-------------
-------------
[[1 1]]
0.112745608306
[[ 0.47485915]]
-------------
-------------
[[1 1]]
0.101568604889
[[ 0.45070745]]
-------------
-------------
[[1 0]]
0.0816118773911
[[ 0.5959904]]
-------------
-------------
[[1 1]]
0.0997642597809
[[ 0.44668615]]
-

-------------
[[0 0]]
0.0386772559279
[[ 0.27812679]]
-------------
-------------
[[0 1]]
0.0851710218112
[[ 0.58727486]]
-------------
-------------
[[0 0]]
0.0403408512718
[[ 0.28404525]]
-------------
-------------
[[1 1]]
0.106570018683
[[ 0.46167092]]
-------------
-------------
[[1 1]]
0.0959986630497
[[ 0.43817499]]
-------------
-------------
[[0 0]]
0.0281689650102
[[ 0.23735612]]
-------------
-------------
[[1 0]]
0.0898768772054
[[ 0.57602623]]
-------------
-------------
[[0 0]]
0.0301225207672
[[ 0.24544865]]
-------------
-------------
[[0 1]]
0.100117509792
[[ 0.55252372]]
-------------
-------------
[[1 0]]
0.0778985443686
[[ 0.6052886]]
-------------
-------------
[[0 0]]
0.0362954246489
[[ 0.26942689]]
-------------
-------------
[[0 0]]
0.0337157058844
[[ 0.25967559]]
-------------
-------------
[[0 1]]
0.0925972483524
[[ 0.5696577]]
-------------
-------------
[[0 1]]
0.0844558081408
[[ 0.58901142]]
-------------
-------------
[[0 1]]
0.0770320487073
[[ 0.60749]]
-

-------------
-------------
[[0 0]]
0.0187126134177
[[ 0.19345601]]
-------------
-------------
[[0 0]]
0.0173803908869
[[ 0.18644244]]
-------------
-------------
[[0 1]]
0.131821481181
[[ 0.48653826]]
-------------
-------------
[[0 0]]
0.0199209793134
[[ 0.19960451]]
-------------
-------------
[[0 0]]
0.0185027528647
[[ 0.19236815]]
-------------
-------------
[[1 1]]
0.0599903425867
[[ 0.34638228]]
-------------
-------------
[[1 0]]
0.118091937229
[[ 0.51401247]]
-------------
-------------
[[1 1]]
0.0617798886791
[[ 0.35151071]]
-------------
-------------
[[0 0]]
0.0155349847516
[[ 0.17626676]]
-------------
-------------
[[0 0]]
0.014428963896
[[ 0.16987621]]
-------------
-------------
[[0 1]]
0.14064542405
[[ 0.4696314]]
-------------
-------------
[[0 0]]
0.016982673173
[[ 0.1842969]]
-------------
-------------
[[0 1]]
0.131812813139
[[ 0.48655514]]
-------------
-------------
[[1 0]]
0.10377883326
[[ 0.54441503]]
-------------
-------------
[[1 0]]
0.0945006151058
[[ 0.56

-------------
-------------
[[0 0]]
0.031994537755
[[ 0.25296062]]
-------------
-------------
[[0 0]]
0.0297132973803
[[ 0.24377571]]
-------------
-------------
[[0 1]]
0.0990030721888
[[ 0.55502119]]
-------------
-------------
[[0 1]]
0.0902624609417
[[ 0.57511776]]
-------------
-------------
[[1 1]]
0.0960807754948
[[ 0.43836235]]
-------------
-------------
[[1 0]]
0.0793459518029
[[ 0.60163848]]
-------------
-------------
[[0 0]]
0.0355439902109
[[ 0.26662329]]
-------------
-------------
[[1 0]]
0.0762087904151
[[ 0.60959306]]
-------------
-------------
[[1 1]]
0.0979274403047
[[ 0.44255495]]
-------------
-------------
[[0 0]]
0.0323616591217
[[ 0.25440778]]
-------------
-------------
[[0 0]]
0.0300541547401
[[ 0.24516996]]
-------------
-------------
[[0 1]]
0.0978418575473
[[ 0.55763848]]
-------------
-------------
[[1 1]]
0.088642744151
[[ 0.42105283]]
-------------
-------------
[[1 0]]
0.0855408856846
[[ 0.58637968]]
-------------
-------------
[[0 0]]
0.031924384371

[[ 0.51816818]]
-------------
-------------
[[1 0]]
0.0536625306615
[[ 0.67239496]]
-------------
-------------
[[1 1]]
0.12856471383
[[ 0.50707931]]
-------------
-------------
[[0 1]]
0.0640626996442
[[ 0.64205392]]
-------------
-------------
[[1 1]]
0.123969064371
[[ 0.49793386]]
-------------
-------------
[[0 1]]
0.0667607711995
[[ 0.634594]]
-------------
-------------
[[0 0]]
0.046080579701
[[ 0.30358056]]
-------------
-------------
[[0 1]]
0.0649646410427
[[ 0.63954295]]
-------------
-------------
[[1 1]]
0.122312077477
[[ 0.49459494]]
-------------
-------------
[[0 0]]
0.041044458078
[[ 0.28651163]]
-------------
-------------
[[0 1]]
0.0716510641737
[[ 0.62144732]]
-------------
-------------
[[0 0]]
0.0422749140702
[[ 0.29077453]]
-------------
-------------
[[1 0]]
0.0627709305171
[[ 0.64568113]]
-------------
-------------
[[1 1]]
0.115711647698
[[ 0.48106475]]
-------------
-------------
[[0 0]]
0.0377315551789
[[ 0.2747055]]
-------------
-------------
[[1 0]]
0.0690

0.0518851829885
[[ 0.67786592]]
-------------
-------------
[[0 0]]
0.051114348639
[[ 0.31973223]]
-------------
-------------
[[1 1]]
0.118265434324
[[ 0.48634439]]
-------------
-------------
[[1 1]]
0.106446386061
[[ 0.46140305]]
-------------
-------------
[[1 0]]
0.066545429855
[[ 0.6351838]]
-------------
-------------
[[0 1]]
0.0695432545776
[[ 0.62705696]]
-------------
-------------
[[0 0]]
0.0445799676344
[[ 0.29859661]]
-------------
-------------
[[1 1]]
0.106140975123
[[ 0.46074065]]
-------------
-------------
[[1 1]]
0.0955276210727
[[ 0.43709866]]
-------------
-------------
[[1 1]]
0.0859707121276
[[ 0.4146582]]
-------------
-------------
[[0 0]]
0.0275115866566
[[ 0.23457019]]
-------------
-------------
[[1 0]]
0.08609874962
[[ 0.58503313]]
-------------
-------------
[[1 0]]
0.0783544835328
[[ 0.60413517]]
-------------
-------------
[[0 1]]
0.081393466671
[[ 0.59653137]]
-------------
-------------
[[1 0]]
0.0648304102378
[[ 0.63991554]]
-------------
------------

-------------
-------------
[[0 1]]
0.0828727031368
[[ 0.59288158]]
-------------
-------------
[[1 1]]
0.092056440471
[[ 0.42908377]]
-------------
-------------
[[1 0]]
0.0773355330358
[[ 0.60671757]]
-------------
-------------
[[0 1]]
0.0768046179413
[[ 0.60806986]]
-------------
-------------
[[1 0]]
0.0641108575013
[[ 0.6419194]]
-------------
-------------
[[0 1]]
0.0642744590551
[[ 0.64146281]]
-------------
-------------
[[0 0]]
0.0439771003767
[[ 0.29657073]]
-------------
-------------
[[0 1]]
0.0625107946685
[[ 0.64641608]]
-------------
-------------
[[0 0]]
0.0448433772623
[[ 0.29947747]]
-------------
-------------
[[1 0]]
0.0556526718074
[[ 0.66637545]]
-------------
-------------
[[0 0]]
0.045516879647
[[ 0.30171801]]
-------------
-------------
[[1 0]]
0.0544258872795
[[ 0.67007308]]
-------------
-------------
[[0 1]]
0.0549553565804
[[ 0.66847215]]
-------------
-------------
[[1 1]]
0.12808642717
[[ 0.50613521]]
-------------
-------------
[[1 1]]
0.115271415005
[[

[[1 1]]
0.135441703272
[[ 0.52046461]]
-------------
-------------
[[0 1]]
0.0509045089249
[[ 0.68092475]]
-------------
-------------
[[0 0]]
0.0497361331218
[[ 0.31539224]]
-------------
-------------
[[0 1]]
0.0501228870666
[[ 0.68338387]]
-------------
-------------
[[0 0]]
0.0499782100344
[[ 0.31615885]]
-------------
-------------
[[0 0]]
0.0463943382309
[[ 0.30461234]]
-------------
-------------
[[0 0]]
0.0430675834116
[[ 0.29348793]]
-------------
-------------
[[0 1]]
0.0568108419431
[[ 0.66292184]]
-------------
-------------
[[0 0]]
0.0437634622003
[[ 0.2958495]]
-------------
-------------
[[1 1]]
0.115048511869
[[ 0.4796843]]
-------------
-------------
[[0 0]]
0.0352855311137
[[ 0.26565215]]
-------------
-------------
[[0 0]]
0.0327554628952
[[ 0.25595102]]
-------------
-------------
[[0 1]]
0.0706024085476
[[ 0.62422771]]
-------------
-------------
[[0 1]]
0.0643400906811
[[ 0.6412798]]
-------------
-------------
[[0 1]]
0.0586347347698
[[ 0.6575537]]
-------------


[[ 0.51691524]]
-------------
-------------
[[1 0]]
0.048436765404
[[ 0.68875487]]
-------------
-------------
[[1 0]]
0.0440644495958
[[ 0.70313488]]
-------------
-------------
[[0 0]]
0.0493223896296
[[ 0.31407766]]
-------------
-------------
[[0 0]]
0.0457802303598
[[ 0.30258959]]
-------------
-------------
[[0 0]]
0.0424925795701
[[ 0.29152214]]
-------------
-------------
[[1 1]]
0.116879454856
[[ 0.4834862]]
-------------
-------------
[[0 1]]
0.0598620866933
[[ 0.65398819]]
-------------
-------------
[[1 0]]
0.0532347616476
[[ 0.67370332]]
-------------
-------------
[[1 0]]
0.0484286119633
[[ 0.68878107]]
-------------
-------------
[[1 1]]
0.127534750438
[[ 0.50504406]]
-------------
-------------
[[0 0]]
0.0390635795638
[[ 0.27951236]]
-------------
-------------
[[1 1]]
0.109550103855
[[ 0.46808141]]
-------------
-------------
[[1 0]]
0.0627164569431
[[ 0.64583491]]
-------------
-------------
[[1 0]]
0.0570512246842
[[ 0.66220946]]
-------------
-------------
[[1 1]]
0

KeyboardInterrupt: 

In [110]:
print("test!!! start")
x_test = np.array([[1,1],[0,1]])
t_test = np.array([0,1])
print(network.predict([1,1]))
print("correct is 0")
print(network.predict(x_test[1]))
print("correct is 1")

test!!! start
[  1.14848897e-05]
correct is 0
[ 0.99998957]
correct is 1


In [112]:
print(network.predict([[0,1]]))

[[ 0.99998957]]


In [113]:
print(network.predict([[1,0]]))

[[ 0.99998753]]


In [114]:
print(network.predict([[0,0]]))

[[  5.73215724e-06]]


In [115]:
print(network.predict([[1,1]]))

[[  1.14848897e-05]]
